#!/usr/bin/env python3
"""
B站 Playwright 登录工具
持久化 Chromium 浏览器上下文，用户扫码登录后 Profile 自动保存，
后续下载通过导出的 Netscape Cookie 文件传给 yt-dlp，无需重复登录。

持久化目录：~/.autoclip/bilibili_browser/
"""

import json
import logging
import os
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

BROWSER_USER_DATA_DIR = Path.home() / '.autoclip' / 'bilibili_browser'
LOGIN_STATE_FILE = BROWSER_USER_DATA_DIR / 'login_state.json'
COOKIES_FILE = BROWSER_USER_DATA_DIR / 'cookies.txt'  # Netscape 格式，供 yt-dlp 使用

# B站登录标志 Cookie
_LOGIN_COOKIES = {'SESSDATA', 'bili_jct', 'DedeUserID'}


def _get_playwright_browsers_path() -> Optional[str]:
    for p in [
        os.path.expanduser('~/Library/Caches/ms-playwright'),
        os.path.expanduser('~/.cache/ms-playwright'),
    ]:
        if p and Path(p).exists():
            return p
    return None


def _setup_playwright_env():
    path = _get_playwright_browsers_path()
    if path:
        os.environ.setdefault('PLAYWRIGHT_BROWSERS_PATH', path)


def _save_login_state(logged_in: bool, cookies: List[dict]):
    BROWSER_USER_DATA_DIR.mkdir(parents=True, exist_ok=True)
    data = {
        'logged_in': logged_in,
        'saved_at': time.time(),
        'cookie_count': len(cookies),
    }
    LOGIN_STATE_FILE.write_text(json.dumps(data), encoding='utf-8')


def _export_netscape_cookies(cookies: List[dict]):
    """将 Playwright cookies 导出为 Netscape 格式供 yt-dlp 使用"""
    BROWSER_USER_DATA_DIR.mkdir(parents=True, exist_ok=True)
    lines = ['# Netscape HTTP Cookie File', '# Generated by autoClip.x\n']
    for c in cookies:
        domain = c.get('domain', '')
        include_subdomain = 'TRUE' if domain.startswith('.') else 'FALSE'
        path = c.get('path', '/')
        secure = 'TRUE' if c.get('secure', False) else 'FALSE'
        expires = int(c.get('expires', 0)) if c.get('expires') and c.get('expires') != -1 else 0
        name = c.get('name', '')
        value = c.get('value', '')
        lines.append(f"{domain}\t{include_subdomain}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    COOKIES_FILE.write_text('\n'.join(lines), encoding='utf-8')
    logger.info(f"已导出 {len(cookies)} 条 Cookie 到: {COOKIES_FILE}")


def get_browser_login_state() -> Dict[str, Any]:
    """读取持久化浏览器的登录状态"""
    if not LOGIN_STATE_FILE.exists():
        return {'logged_in': False, 'age_hours': None, 'cookie_count': 0, 'valid': False}
    try:
        data = json.loads(LOGIN_STATE_FILE.read_text())
        age = (time.time() - data.get('saved_at', 0)) / 3600
        return {
            'logged_in': data.get('logged_in', False),
            'age_hours': round(age, 1),
            'cookie_count': data.get('cookie_count', 0),
            'valid': data.get('logged_in', False) and age < 7 * 24,
        }
    except Exception:
        return {'logged_in': False, 'age_hours': None, 'cookie_count': 0, 'valid': False}


def get_cookies_file() -> Optional[Path]:
    """返回可用的 Netscape Cookie 文件路径，不可用时返回 None"""
    state = get_browser_login_state()
    if state.get('valid') and COOKIES_FILE.exists():
        return COOKIES_FILE
    return None


def open_login_window_persistent(timeout_sec: int = 300) -> bool:
    """
    打开可见 Chromium 窗口（持久化 Profile），
    等待用户登录 B站 后保存 Profile 并导出 Cookie 文件。
    """
    _setup_playwright_env()
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        logger.error('playwright 未安装，请执行: pip install playwright && playwright install chromium')
        return False

    BROWSER_USER_DATA_DIR.mkdir(parents=True, exist_ok=True)
    logger.info(f'启动持久化浏览器窗口，数据目录: {BROWSER_USER_DATA_DIR}')

    try:
        with sync_playwright() as pw:
            ctx = pw.chromium.launch_persistent_context(
                user_data_dir=str(BROWSER_USER_DATA_DIR),
                headless=False,
                args=[
                    '--no-sandbox',
                    '--disable-blink-features=AutomationControlled',
                    '--start-maximized',
                ],
                user_agent=(
                    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
                    'AppleWebKit/537.36 (KHTML, like Gecko) '
                    'Chrome/122.0.0.0 Safari/537.36'
                ),
                locale='zh-CN',
                timezone_id='Asia/Shanghai',
            )
            ctx.add_init_script(
                "Object.defineProperty(navigator,'webdriver',{get:()=>undefined});"
                "window.chrome={runtime:{}};"
            )
            page = ctx.new_page()
            page.goto('https://www.bilibili.com/', wait_until='domcontentloaded', timeout=15000)

            deadline = time.time() + timeout_sec
            logged_in = False
            while time.time() < deadline:
                page.wait_for_timeout(2000)
                cookie_names = {c['name'] for c in ctx.cookies()}
                if _LOGIN_COOKIES.issubset(cookie_names):
                    logged_in = True
                    logger.info('检测到 B站 登录 Cookie（SESSDATA / bili_jct / DedeUserID）')
                    break

            all_cookies = ctx.cookies()
            _save_login_state(logged_in, all_cookies)
            if logged_in:
                _export_netscape_cookies(all_cookies)
                logger.info('持久化登录完成，Cookie 文件已导出')
            else:
                logger.warning(f'登录超时（{timeout_sec}s），未检测到有效 Cookie')
            ctx.close()
            return logged_in

    except Exception as e:
        logger.error(f'浏览器登录流程出错: {e}')
        return False


def clear_login_state():
    """清除登录状态和 Cookie 文件"""
    import shutil
    if BROWSER_USER_DATA_DIR.exists():
        shutil.rmtree(BROWSER_USER_DATA_DIR, ignore_errors=True)
    logger.info('B站登录状态已清除')
